//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex5
{
    using System;
    using System.Collections.Generic;
    
    public partial class manutencao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public manutencao()
        {
            this.manutencaoItems = new HashSet<manutencaoItem>();
        }
    
        public string matricula { get; set; }
        public int km { get; set; }
        public Nullable<decimal> valorTotal { get; set; }
        public System.DateTime data { get; set; }
    
        public virtual veiculo veiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<manutencaoItem> manutencaoItems { get; set; }
    }
}
