//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex5
{
    using System;
    using System.Collections.Generic;
    
    public partial class manutencaoItem
    {
        public string matricula { get; set; }
        public int km { get; set; }
        public int nLinha { get; set; }
        public decimal valor { get; set; }
    
        public virtual manutencao manutencao { get; set; }
    }
}
